{{- if .Values.rasanlu.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasanlu-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasanlu-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: rasanlu-{{ .Release.Name }}
    spec:
      volumes:
      {{- if .Values.rasanlu.pvc.enabled }}
        - name: rasanlu-data
          persistentVolumeClaim:
            claimName: rasanlu-{{ .Release.Name }}-data
      {{- end }}
      containers:
        - image: {{ .Values.rasanlu.image.repository }}:{{ .Values.rasanlu.image.tag }}
          args: ["run", "--enable-api"{{- if .Values.rasanlu.token }}, "--auth-token", "{{ .Values.rasanlu.token }}"{{- end }}{{- if .Values.rasanlu.debug_log }}, "-vv"{{- end }}]
          imagePullPolicy: {{ .Values.rasanlu.image.imagePullPolicy }}
          name: rasanlu
          ports:
            - containerPort: {{ .Values.rasanlu.service.port }}
        {{- if $.Values.resources }}
          resources:
{{ toYaml $.Values.rasanlu.resources | indent 12 }}
        {{- end }}
          volumeMounts:
          {{- if .Values.rasanlu.pvc.enabled }}
            - mountPath: /app/projects
              name: rasanlu-data
              subPath: projects
            - mountPath: /app/data
              name: rasanlu-data
              subPath: data
          {{- end }}
{{- end -}}
